#ifndef RANDOM_H
#define RANDOM_H

#define MIN(a, b) ((a) < (b) ? (a) : (b))
#define CEIL(a, b) (((a) / (b)) + ((a) % (b) != 0))

#include <stdint.h>

#define UINT_TYPE(bitsize) uint##bitsize##_t

#define RANDOM_UINT(bitsize, upper_bound) \
    do { \
        UINT_TYPE(bitsize) result = RET_ERR; \
        if (random((uint8_t *)&result, sizeof(result), (uint8_t)((upper_bound) - 1)) != RET_OK) { \
            return -1; \
        } \
        return result; \
    } while(0)

typedef enum {
    RET_OK = 0,
    RET_ERR = -1
} ret_t;

/**
 * @brief Initialize the internal random generator state.
 */
void random_init(void);

/**
 * @brief Generate random bytes.
 * @param[out] buf Output buffer.
 * @param length Number of bytes to generate.
 * @param upper_bound Inclusive upper bound applied to each generated byte.
 * 
 * @return ret_t RET_OK on success, RET_ERR on failure.
 */
ret_t random(uint8_t * buf, uint32_t len, uint8_t upper_bound);

#endif
