#ifndef RANDOM_H
#define RANDOM_H

#define UINT_TYPE(bitsize) uint##bitsize##_t /**< Type for unsigned integer of specified bit size */

#include <stdint.h>

/**
 * @brief Calculate the minimum of two values.
 * @param a First value.
 * @param b Second value.
 * @return The minimum of a and b.
 */
inline uint32_t u32_min(uint32_t a, uint32_t b) {
    return (a < b) ? a : b;
}

/**
 * @brief Calculate the ceiling of the division of two values.
 * @param a Numerator.
 * @param b Denominator.
 * @return The ceiling of a divided by b.
 */
__always_inline
inline uint32_t u32_ceil(uint32_t a, uint32_t b) {
    return (a / b) + (uint32_t) ((a % b) != 0);
}

/**
 * @brief Return type for functions that can fail.
 */
typedef enum {
    RET_OK = 0, /**< Success code */
    RET_ERR = -1 /**< Failure code */
} ret_t;

/**
 * @brief Initialize the internal random generator state.
 */
void random_init(void);

/**
 * @brief Generate random bytes.
 * @param[out] buf Output buffer.
 * @param length Number of bytes to generate.
 * @param upper_bound Inclusive upper bound applied to each generated byte.
 * 
 * @return ret_t RET_OK on success, RET_ERR on failure.
 */
ret_t random(UINT_TYPE(8)* buf, UINT_TYPE(32) len, UINT_TYPE(8) upper_bound);

/** 
 * @brief Static inline implementations used by the RANDOM_UINT macro. These 
 * do not return on failure.
 */
static inline UINT_TYPE(64) _random_uint_impl_64(UINT_TYPE(64) upper_bound)
{
    UINT_TYPE(64) result = 0;
    UINT_TYPE(64) random_err = RET_ERR;
    random_err = random((UINT_TYPE(8)*) &result, sizeof(result), (UINT_TYPE(8))((upper_bound) - 1));
    __cmp_and_panic(random_err, RET_OK, !=);
    return result;
}

static inline UINT_TYPE(32) _random_uint_impl_32(UINT_TYPE(32) upper_bound)
{
    UINT_TYPE(32) result = 0;
    UINT_TYPE(32) random_err = RET_ERR;
    random_err = random((UINT_TYPE(8)*) &result, sizeof(result), (UINT_TYPE(8))((upper_bound) - 1));
    __cmp_and_panic(random_err, RET_OK, !=);
    return result;
}

static inline UINT_TYPE(16) _random_uint_impl_16(UINT_TYPE(16) upper_bound)
{
    UINT_TYPE(16) result = 0;
    UINT_TYPE(16) random_err = RET_ERR;
    random_err = random((UINT_TYPE(8)*) &result, sizeof(result), (UINT_TYPE(8))((upper_bound) - 1));
    __cmp_and_panic(random_err, RET_OK, !=);
    return result;
}

static inline UINT_TYPE(8) _random_uint_impl_8(UINT_TYPE(8) upper_bound)
{
    UINT_TYPE(8) result = 0;
    UINT_TYPE(8) random_err = RET_ERR;
    random_err = random((UINT_TYPE(8)*) &result, sizeof(result), (UINT_TYPE(8))((upper_bound) - 1));
    __cmp_and_panic(random_err, RET_OK, !=);
    return result;
}

#define RANDOM_UINT(bitsize, upper_bound) _random_uint_impl_##bitsize((upper_bound))

#endif
